Brought Up To Standard
Dhii/validation-abstract pull request #10
Opened 2017-09-04 17:16 UTC by XedinUnknown

Aims to incorporate solution for #8.

2017-09-04 17:22 UTC, mecha requested changes
The second requested change in #8 is still not fulfilled in this PR.

2017-09-04 17:23 UTC, XedinUnknown commented
Sorry, forgot to mention that it's WIP. Early review, so to speak.

2017-09-05 07:26 UTC, mecha commented on src/SpecAwareTrait.php
> +     * @var mixed
Typehint as `array|Traversable|null`

2017-09-05 07:26 UTC, mecha commented on src/SpecAwareTrait.php
> +     * @return array|Traversable The spec.
Add `null` as a possible return type.

2017-09-05 07:33 UTC, mecha approved these changes

2017-09-10 18:34 UTC, mecha commented
The doc tag order is off (such as in `AbsractCompositeValidator`). I suggest running the CS fixer; afaik it should clean these up.

2017-09-15 09:57 UTC, mecha approved these changes
LGTM

2017-09-15 09:58 UTC, XedinUnknown commented
@mecha, CS fixer doesn't seem to care whether param docs come before or after the `@since`. If it can't be done automatically, I wouldn't bother.

2017-09-15 09:59 UTC, merged